### PR TITLE
Feat: Updated Docs

### PR DESCRIPTION
**Pull request by A1994SC**
This PR is to bring the docs into line with the recommended style from hashicorp, using their tool [tfplugindocs](https://github.com/hashicorp/terraform-plugin-docs)

I tried to keep the docs feeling mostly the same well being within "spec", please let me know if any of the new docs are out of date. I mostly tried to keep what was still valid arguments and the descriptions for those arguments.

### CODE REVIEW

**Comment by Vad1mo** [comment]
@A1994SC thank you for your contribution. this is great. 
Is there a need or option to automate things, with eg. gh action or is it a one time manual thing?

**Comment by A1994SC** [comment]
No problem to all! As for actions I am not too sure, that part is something that I have not dug to much into, but I did find [this](https://github.com/terraform-docs/gh-actions) which seems to be a step in the right direction.

**Comment by A1994SC** [comment]
So I used the command `tfplugindocs` at the root of the repo to get all the files generated from the `templates/*.tmpl` files.

**Comment by A1994SC** [comment]
@Vad1mo did you have any questions?

**Review by Vad1mo — APPROVED** [review]

**Comment by A1994SC** [comment]
Is the failing build, sonarcloud, something I should worry about?

**Comment by flbla** [comment]
Hi,
@A1994SC, thank you! It looks great!
I agree with @Vad1mo, It would be even better if we could implement a gh action at the time of release. 
I'm concerned that I might forget to update the template and launch the CLI every time an update is made to the documentation.

**Comment by flbla** [comment]
maybe a gh action executed on pull request

**Comment by A1994SC** [comment]
@flbla so taking a look at what hashicorp does it seem they regenerate the docs: [link](https://github.com/hashicorp/terraform-provider-awscc/blob/main/.github/workflows/tfplugindocs-check.yml) , [make](https://github.com/hashicorp/terraform-provider-awscc/blob/main/GNUmakefile#L52-L61)

So I can add a similar action if you would like.

**Comment by flbla** [comment]
it seems good!
let me know if you need help
thank you!

**Comment by A1994SC** [comment]
@flbla Added a new action and it works locally can you let me know what you think?

**Comment by A1994SC** [comment]
I also only added the make setting for generating the docs, idk enough on the setup of this project, and golang in general, to do that lol

**Review by flbla — APPROVED** [review]
LGTM

**Comment by flbla** [comment]
@A1994SC : thank you 👍

**Comment by A1994SC** [comment]
@flbla No problem! Glad to contribute!

**Pull request merged**
