### PR TITLE
fix nil pointer dereference issue(#229)

### PR DESCRIPTION
**Pull request by feiyunzhou**
Closes: [#229]

Signed-off-by: feiyunzhou <feiyun.zhou@gmail.com>

### CODE REVIEW

**Review by OrlinVasilev — APPROVED** [review]

**Comment by OrlinVasilev** [comment]
@timofurrer and @Gaardsholt can you take a look please!

**Comment by timofurrer** [comment]
LGTM 🎉

**Review by timofurrer — APPROVED** [review]

**Review by flbla — APPROVED** [review]

**Comment by feiyunzhou** [comment]
@OrlinVasilev @Vad1mo The latest release was on May 5, published on 6 months ago, so could you please publish a new release?

**Comment by OrlinVasilev** [comment]
@feiyunzhou can you open new issue about that so we can discuss about releases and proceed with this! Thank you!

**Pull request merged**
