### PR TITLE
Error handling project and members

### LINKED ISSUE #235: Provider does not handle missing members of project correctly
**Describe the bug**
When creating a project membership via terraform and subsequently deleting the membership (i.e. removign the user from the project) via webUI/manually, the provider crashes with the error that the user cannot be found, instead of suggesting that they should be added back to it.

**To Reproduce**
Deploy a harbor project and assign a user as member:
```hcl
resource "harbor_project" "test" {
  name = "test-project"
}

resource "harbor_project_member_user" "user" {
  for_each   = toset(local.admins)
  project_id = harbor_project.test.id
  user_name  = "test@example.com"
  role       = "projectadmin"
}
```
Now, delete the user from the project via the project's members tab.

On the next run, you should see an error:
```
harbor_project_member_user.user: Refreshing state... [id=/projects/1336/members/1020]

╷
│ Error: Resource not found /projects/1336/members/1020
│
│   with harbor_project_member_user.user,
│   on main.tf line 7, in resource "harbor_project_member_user" "user":
│    7: resource "harbor_project_member_user" "user" {
│
╵
```

**Expected behavior**
The provider should catch the error and register a required change to the project's members, re-adding the user.

**Additional Info**
Harbor Provider: `v3.7.1`
Terraform version: `1v.2.3`

### PR DESCRIPTION
**Pull request by naitmare01**
This PR introduces error-handling to gracefully update and recreate resources that have been altered outside of Terraform.

- project
- project_member_group
- project_member_user

This fixes #235

### CODE REVIEW

**Comment by flbla** [comment]
Hi @naitmare01,
thanks

there is an issue with the SendRequest function : https://github.com/goharbor/terraform-provider-harbor/blob/main/client/client.go#L88 
instead of return `resp.StatusCode` it return 0 when the expected status code is different of the status code.

if we fix that, it will be handle by : https://github.com/goharbor/terraform-provider-harbor/blob/main/provider/resource_project.go#L96 `if respCode == 404 && err != nil` in the resourceProjectRead function.

same for other resources

**Review by flbla — CHANGES_REQUESTED** [review]
we need to fix SendRequest function

**Comment by naitmare01** [comment]
@flbla I agree that `SendRequest` needs to be fixed. That explains why I was having trouble getting proper response-code when I wrote this PR.

Are there any active issue or PR coming to fix that? I suggest we wait with this PR until that is fixed.

**Comment by flbla** [comment]
There is no PR yet. I discovered the bug will reviewing your PR.

**Comment by flbla** [comment]
@naitmare01 : https://github.com/goharbor/terraform-provider-harbor/pull/363
I did some tests, it seems better.

**Comment by naitmare01** [comment]
LGTM!

**Comment by flbla** [comment]
I merged #363 
i think we can return nil here : https://github.com/goharbor/terraform-provider-harbor/pull/356/files#diff-8872ceb4daebf7b2223fb0a0341bd06991a1758ec72c38dcf9fc66a396638533R98 to handle it

**Comment by naitmare01** [comment]
> I merged #363 i think we can return nil here : https://github.com/goharbor/terraform-provider-harbor/pull/356/files#diff-8872ceb4daebf7b2223fb0a0341bd06991a1758ec72c38dcf9fc66a396638533R98 to handle it

I think it will work fine. But isn't it more clear if we actually return what the error is about instead of `nil`?

**Comment by flbla** [comment]
if we return an error, it will not handle resources deleted outside of terraform
maybe I misunderstood what you want to do ?

**Comment by naitmare01** [comment]
It was I who misunderstood you. :) 

Changed to `nil` in the latest commit.

**Comment by naitmare01** [comment]
@flbla are you waiting for any more changes from me?

**Review by flbla — APPROVED** [review]

**Pull request merged**
