### PR TITLE
feat: add oidc group filter

### LINKED ISSUE #320: Add oidc group filter
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add oidc group filter, present since 2.7.0, [see PR](https://github.com/goharbor/harbor/pull/17736)

**Describe alternatives you've considered**
None

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by jobcespedes**
Fixes #320

### CODE REVIEW

**Comment by Vad1mo** [comment]
@jobcespedes please resolve the issue with DCO.

**Comment by jobcespedes** [comment]
Done!

**Review by Vad1mo — APPROVED** [review]

**Comment by Vad1mo** [comment]
> Done!
@jobcespedes, looks like something didn't work out as expected. the DCO is still red.

**Comment by jobcespedes** [comment]
Fixed. I used a different email. Now DCO is green

**Review by flbla — APPROVED** [review]

**Review by OrlinVasilev — APPROVED** [review]

**Comment by OrlinVasilev** [comment]
@jobcespedes congrats on merging your first PR here :)) welcome to the party :)

**Pull request merged**
