### PR TITLE
to enable instead of to enabled

### PR DESCRIPTION
**Pull request by Brazeg**

### CODE REVIEW

**Comment by Brazeg** [comment]
sure, i've added a signoff

**Review by OrlinVasilev — APPROVED** [review]

**Comment by OrlinVasilev** [comment]
@Brazeg still not ok :(

**Review by flbla — APPROVED** [review]

**Comment by flbla** [comment]
Hi,
@Brazeg , thank you!

**Comment by OrlinVasilev** [comment]
@Brazeg congrats on merging your first PR here :)

**Pull request merged**
